# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.protos import prompt_builder_pb2 as rpc_dot_protos_dot_prompt__builder__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rpc/protos/prompt_builder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PromptBuilderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildPrompt = channel.unary_unary(
                '/prompt_builder.PromptBuilder/BuildPrompt',
                request_serializer=rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptRequest.SerializeToString,
                response_deserializer=rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptResponse.FromString,
                _registered_method=True)


class PromptBuilderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuildPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildPrompt,
                    request_deserializer=rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptRequest.FromString,
                    response_serializer=rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prompt_builder.PromptBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prompt_builder.PromptBuilder', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromptBuilder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prompt_builder.PromptBuilder/BuildPrompt',
            rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptRequest.SerializeToString,
            rpc_dot_protos_dot_prompt__builder__pb2.BuildPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
